Makefiles
YetAnotherSpieskowcy/Carcassonne-Visualiser pull request #7
Opened 2024-09-03 10:27 UTC by BognaLew

2024-09-03 11:38 UTC, bstrzelecki submitted a review, later dismissed

2024-09-03 11:38 UTC, bstrzelecki commented on make.sh
> +    go run . $2 -tags sdl
```suggestion
    go run -tags sdl . $1
```

2024-09-03 11:38 UTC, bstrzelecki commented on make.sh
> +        run
```suggestion
        run $2
```

2024-09-03 11:45 UTC, bstrzelecki submitted a review, later dismissed

2024-09-03 15:35 UTC, Lenetis commented on README.md
> +./make.ps1 run _log-filename_
```suggestion
Set-ExecutionPolicy Bypass -Scope Process -Force
./make.ps1 run _log-filename_
```

2024-09-03 15:35 UTC, Lenetis commented on README.md
> +./make.ps1 update
```suggestion
Set-ExecutionPolicy Bypass -Scope Process -Force
./make.ps1 update
```

2024-09-03 15:35 UTC, Lenetis commented on README.md
> +2. Download [SDL2 binary](https://github.com/libsdl-org/SDL/releases) and put the dll file in the system directory.
```suggestion
2. Download [SDL2 binary](https://github.com/libsdl-org/SDL/releases) and add the path to the dll file to the system PATH environment variable.
```

2024-09-04 10:14 UTC, bstrzelecki approved these changes

2024-09-04 17:35 UTC, Jackenmen requested changes

2024-09-04 17:35 UTC, Jackenmen commented on main.go
> +		return
Exit with a non-zero exit code on failure.
```suggestion
		os.Exit(2)
```

2024-09-04 17:35 UTC, Jackenmen commented on make.sh
Arguably, this could be a _real_ Makefile with the log file argument passed as an env var. But well, this will do :P

2024-09-04 17:35 UTC, Jackenmen commented on make.sh
> +fi
nit: end file with an empty line
```suggestion
fi

```

2024-09-04 17:35 UTC, Jackenmen commented on make.sh
> +        run $2
Fix handling of filenames with spaces:
```suggestion
        run "$2"
```

2024-09-04 17:35 UTC, Jackenmen commented on make.sh
> +    go run -tags sdl . $1
Fix handling of filenames with spaces:
```suggestion
    go run -tags sdl . "$1"
```

2024-09-04 17:35 UTC, Jackenmen commented on make.ps1
> +    & go get -u "github.com/YetAnotherSpieskowcy/Carcassonne-Engine@main"
Exit-On-Fail needs to be called after each shell command:
```suggestion
    & go get -u "github.com/YetAnotherSpieskowcy/Carcassonne-Engine@main"
    Exit-On-Fail $LASTEXITCODE
```

2024-09-04 17:35 UTC, Jackenmen commented on make.ps1
> +    Exit-ON-Fail $LASTEXITCODE
nit: inconsistent casing
```suggestion
    Exit-On-Fail $LASTEXITCODE
```

2024-09-04 17:35 UTC, Jackenmen commented on make.ps1
> +        Exit-ON-Fail $LASTEXITCODE
nit: inconsistent casing
```suggestion
        Exit-On-Fail $LASTEXITCODE
```

2024-09-04 17:35 UTC, Jackenmen commented on make.sh
> +#!/bin/sh
Run sh with the `-e` flag to automatically exit on a non-zero exit code:
```suggestion
#!/bin/sh -e
```

2024-09-04 17:35 UTC, Jackenmen commented on make.sh
> +if [ $1 == "run" ]; then
POSIX sh (which is the shell you listed in the shebang) requires using single equal sign for equality checks:
```suggestion
if [ $1 = "run" ]; then
```

2024-09-04 17:35 UTC, Jackenmen commented on make.sh
> +elif [ $1 == "update" ]; then
POSIX sh (which is the shell you listed in the shebang) requires using single equal sign for equality checks:
```suggestion
elif [ $1 = "update" ]; then
```

2024-09-06 17:26 UTC, Lenetis submitted a review, later dismissed

2024-09-06 23:41 UTC, Jackenmen approved these changes
There was an unapplied suggestion so I applied that. Looks good to me now.

2024-09-07 09:39 UTC, bstrzelecki approved these changes

2024-09-07 15:50 UTC, merged